# Generated by Django 3.0.7 on 2020-07-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCRUPro', '0002_auto_20200702_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='create_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
