# Generated by Django 3.0 on 2020-11-04 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BCRUPro', '0002_invitebids'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitBids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.TextField(unique=True)),
                ('price', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('invite_bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BCRUPro.InviteBids')),
            ],
        ),
    ]
