# Generated by Django 3.0.7 on 2020-07-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('BCRUPro', '0003_auto_20200716_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.User'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
