# Generated by Django 3.0 on 2021-08-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCRUPro', '0003_auto_20210415_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overview',
            field=models.TextField(default='overview'),
        ),
    ]
