# Generated by Django 3.0 on 2021-09-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCRUPro', '0004_product_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('logo', models.TextField(unique=True)),
                ('overview', models.TextField(default=None)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
