# Generated by Django 3.0 on 2021-10-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCRUPro', '0008_auto_20210902_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('image_name', models.TextField()),
                ('temperature_limit', models.IntegerField(default=0)),
                ('temperature_data', models.IntegerField(default=0)),
                ('humidity_limit', models.IntegerField(default=0)),
                ('humidity_data', models.IntegerField(default=0)),
            ],
        ),
    ]
