# Generated by Django 3.0 on 2021-10-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCRUPro', '0009_crops'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='herbicide',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crops',
            name='nitrogen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crops',
            name='ph_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='crops',
            name='humidity_data',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='crops',
            name='humidity_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='crops',
            name='temperature_data',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='crops',
            name='temperature_limit',
            field=models.FloatField(default=0.0),
        ),
    ]
