# Generated by Django 3.0 on 2021-10-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCRUPro', '0010_auto_20211014_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='deploy_status',
            field=models.BooleanField(default=False),
        ),
    ]
